//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentLog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Incident
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Date of Incident")]
        public Nullable<System.DateTime> IncidentDate { get; set; }
        [Required]
        [Display(Name = "Time of Incident")]
        public Nullable<System.TimeSpan> IncidentTime { get; set; }
        [Display(Name = "Reporting Unit")]
        public Nullable<int> Unit { get; set; }
        [Display(Name = "Type of Incident")]
        public string Incident1 { get; set; }
        [Display(Name = "Summary of Incident")]
        public string Summary { get; set; }
    
        public virtual UnitType UnitType { get; set; }
    }
}
